### ISSUE TITLE
Broken functions

### ISSUE THREAD

**Issue by gchoqueux** [iTowns/itowns#296]
This issue lists the broken functions since #244 

- [x] ~~wrong texture in WMTS (see South Pole) (suspect #244)~~
- [x] ~~There's no more fog (suspect #239) resolve in #447~~
- [x]  ~bad update matrix OBBHelper (suspect #294)~
- [x]  ~~pick mouse Coordinate is wrong~~ (suspect #246 )
- [x]  ~~the tile's OBB are bigger than tile's geometry (Too many tiles are displayed)  (suspect #303 )~~ resolve in #331

**Comment by Jeremy-Gaillard** [comment]
I'll add:
- [x] ~~The globe disappears when zooming in in some places (for example: east US coast)~~
